version: "3"
services:
    app:
        build:
            dockerfile: Dockerfile
            #   a dockerfájl alapján amit csináltunk   
            context: .
            # a gyökérben
        volumes:
            - /app/node_modules
            - .:/app
                # ezeket csatolja hozzája
        ports:
                - "3000:3000"
                # a saját gépem 3000-es portja legyen
        links:
            - mongo    
    mongo:
        container_name: mongo
        image: mongo:latest
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"                